# 网关中心服务配置
server:
  port: 8061

# 日志配置
logging:
  level:
#    root: debug
    com.li.cloud.common.basecurd.dao : debug
    com.li.cloud.gateway.dao: debug

spring:
  application: # 路由中心的服务名称
    name: gateway-center
  datasource: # Mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yunding?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password:
  redis: # Redis 连接
    host: 10.101.66.107
    port: 6379

# 服务治理配置
eureka:
  client:
    enabled: true
    service-url: # 注册中心地址
      defaultZone: http://registry1:8051/cloud/registry/center/eureka/,http://registry2:8052/cloud/registry/center/eureka/

# 断熔配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 # 设置网关路由转发请求的HystrixCommand执行超时时间，单位：毫秒

# 负载均衡配置
ribbon:
  ConnectTimeout: 500 # 路由转发请求时，创建请求连接超时时间
  ReadTimeout: 4000 # 路由转发请求时，请求处理的超时时间
  OkToRetryOnAllOperations: true # 所有请求都重试操作
  MaxAutoRetriesNextServer: 2 # 切换实例重试次数
  MaxAutoRetries: 1 # 当前实例重试次数

# 路由网关配置
zuul:
  ignored-services: "*"
  host:
    connect-timeout-millis: 1000
    socket-timeout-millis: 10000
  routes: # 路由转发配置
    server-tool:
      path: /tool/**
      serverceId: server-tool
    yunding-online:
      path: /online/**
      serverceId: yunding-online
  SendErrorFilter:
    error:
      disable: true
